In [1]:
import pandas as pd

In [2]:
fake = pd.read_csv("Fake.csv")
true = pd.read_csv("True.csv")

In [3]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
fake["label"] = 0
true["label"] = 1

In [6]:
true.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [7]:
news = pd.concat([fake, true], ignore_index=True)

In [8]:
news = news.sample(frac=1, random_state=42).reset_index(drop=True)

In [9]:
news.head()

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1

In [10]:
news.shape

(44898, 5)

In [11]:
#Data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\navee\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [12]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [13]:
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# 3000 random rows
messages_sample = news.sample(n=3000, random_state=42).reset_index(drop=True)

ps = PorterStemmer()
stop_words = set(stopwords.words('english'))

corpus = []

for i in range(len(messages_sample)):
    review = re.sub('[^a-zA-Z]', ' ', messages_sample['text'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if word not in stop_words]
    review = ' '.join(review)

    corpus.append(review)

In [14]:
corpus

['well take long short time sinc american kinda sorta elect donald trump pussygrabb chief trump appoint bona fide white nationalist high level posit perform numer action month ago consid extrem unlik nightmar scenario latest seem muslim registri media told us trump seriou might actual happen trump regim muslim immigr come unit state trump pal call terror prone countri soon regist check regularli govern trump advis kansa secretari state kri kobach way kobach say trump administr aim quickli wast taxpay dollar wall move forward propos get thing roll registri immigr muslim countri reuter report kansa secretari state kri kobach help write tough immigr law arizona elsewher said interview trump polici advis also discuss draft propos consider reinstat registri immigr muslim countri kobach media report say key member trump transit team said particip regular confer call dozen trump immigr advis past two three month trump transit team respond request confirm kobach role presid elect commit follow specif recommend advisori group nation secur entri exit registr system design part kovach bush administr ineffect program singl muslim manag convict singl person anyth relat terror campaign trump suggest monitor mosqu ad would need lot system extend beyond databas keep eye muslim kobach say advis also look get construct border wall move without approv congress say happen reappropri exist fund acknowledg futur fiscal year requir addit appropri trump shown us charact choos part administr action sinc elect say give chanc see govern answer presid elect pussygrabb repeatedli demonstr complet lack moral compass decenc hand size us oppos donald trump everi turn protect progress america made last fifti year defend nation everi way intern enemi recent john oliv remind us allow live becom normal keep remind normal oliv said klan back misogynist internet troll go deliv next state union address normal truer word never spoken featur imag via getti imag matthew busch',
 'reuter republican lawmak devin nune investig whether obama administr offici use classifi intellig report discredit donald trump campaign team could backfir congressman presid sourc familiar report said report contain evid aid former democrat presid barack obama act improperli sourc said indic trump associ may violat obscur law logan act prohibit unauthor u citizen negoti foreign govern disput unit state spi report also relev investig special counsel robert mueller conclus u intellig agenc russia work tilt last novemb elect republican trump favor said sourc spoke condit anonym mueller offic declin comment russia u sanction right abus annex crimea repeatedli deni alleg elect meddl trump deni possibl collus campaign moscow issu loom new presid nune chairman u hous intellig committe trump alli met secretli earlier year white hous intellig aid accus obama offici request name u citizen seen intercept commun russian foreign white hous respond request comment name would routin censor intellig agenc intercept nune charg obama aid leak inform tri undermin trump run presid spokesman unit nation ambassador samantha power nune republican accus dig polit dirt said read intellig report part normal duti spokesman former obama nation secur advis susan rice republican also accus misus intellig respond request comment mueller investig meet convers trump associ russian foreign offici businessmen includ trump advis son law jare kushner presid eldest son donald trump jr former trump campaign chairman paul manafort former nation secur advis michael flynn obviou question meet convers set said one sourc set purpos agenda approv brief afterward signal intellig might shed light repres trump associ respond request comment democrat lawmak said nune other made assert leak distract attent two congression investig mueller probe russian matter nation secur agenc mask name u citizen intercept offici necessari secur clearanc request intellig purpos unmask american extrem sensit unmask polit oppon realli problemat said congression offici also speak condit anonym obama offici ask name fail justifi request warrant investig offici said ask hard evid power aid misus intellig polit purpos leak inform media offici declin comment',
 'washington reuter presid donald trump said friday church texa abl receiv money feder emerg manag agenc help victim hurrican harvey trump tweet church texa entitl reimburs fema relief fund help victim hurrican harvey like other trump tweet follow lawsuit file three texa church seek feder aid repair sever damag structur harvey clear whether church provid aid victim complaint file monday feder court houston texa church said would like appli aid would futil fema public assist program categor exclud claim violat constitut right freeli exercis religion said fema ban provid relief least half build space use religi purpos polici also enforc hurrican katrina hurrican sandi contradict recent u suprem court decis make easier religi group get public aid becket nonprofit advoc religi freedom repres church said principl appli feder fema relief harvey victim principl govern discrimin basi religi statu unapologet fema daniel blomberg lawyer becket said phone interview fema spokeswoman said email would inappropri discuss pend litig texa church su rockport first assembl god rockport lost roof steepl suffer structur damag harvest famili church cypress hi way tabernacl cleveland flood case harvest famili church et al v feder emerg manag agenc et al u district court southern district texa',
 'print journal longstand paper struggl sinc advent internet increas competit face blog op ed site combin poor understand market new platform combin realli caus struggl journal industri certain level journalist thank trump despit unleash war freedom press never seen nation histori boon busi massiv public backlash trump fake news armi result thirst fact inform take new york time exampl first quarter nyt sign new subscrib period histori stock percent digit advertis revenu went nearli percent donald trump say fail nyt go go busi today answer soon around year look go anyplac anytim soon specif tweet question much longer fail nytim big loss massiv unfund liabil non exist sourc remain busi donald j trump realdonaldtrump august repli new york time complet demolish whatev littl remnant digniti trump left point incorrect nyt busi thrive ever paid sub million grow profit incom revenu pic twitter com ne fqu rvw nytco commun nytimescomm august went establish verac length particular articl trump took issu unfortun nyt trump read anyth charact seem somewhat unlik broken read featur imag via zach gibson pool getti imag',
 'washington reuter presid donald trump brief friday hous speaker paul ryan statu vote republican bill replac obamacar white hous said amid sign measur might enough support pass presid speaker ryan come visit updat bill white hous spokesman sean spicer told brief continu discuss way forward speaker updat effort spicer said vote schedul p edt gmt downplay prospect loss might undermin trump effort push tax reform u congress',
 'washington reuter individu steal classifi inform u govern enemi state must punish forc white hous homeland secur advis said wednesday tom bossert remark among first made publicli sinc becom white hous homeland secur advis character cyber secur u govern around world gener disarray need find peopl hold account absolut unwav bossert said remark center strateg intern studi think tank washington c peopl taken thing taken like snowden other absolut enemi state period bossert said need caught punish treat refer edward snowden former u nation secur agenc contractor whose leak classifi inform trigger intern furor reach u spi oper bossert whose role includ special emphasi cyber secur made remark week wikileak publish document relat secret cia hack tool investig believ document like provid contractor cia employe two u offici told reuter last week would third high profil public case recent year insid pilfer larg tranch secret u intellig agenc recent cia leak show intensifi u govern effort prevent leak insid threat larg fail accord cyber secur profession intellig offici januari former presid barack obama shorten prison sentenc chelsea man former u militari intellig analyst leak hundr thousand state depart cabl wikileak man due releas may serv seven year sentenc obama defend lenienc say justic serv drew critic republican said move could embolden potenti leaker bossert said agenc compani respons institut control continu employe screen monitor system guard insid threat character cyber secur gener disarray bossert said obama administr enough forc combat deter grow crimin nation state threat feel like awoken long eight year nap found world fire bossert said presid donald trump annual budget propos expect releas thursday would reflect white hous plan priorit cyber secur across feder govern bossert said also confirm media report rob joyc nation secur agenc top hacker join white hous cyber secur coordin',
 '',
 'senat rand paul appear bill hemmer fox news show discuss import fight fisa law prevent us govern unlaw spi collect inform american tax reform done deal wind back senat rand paul came swing obama administr paul said want answer mueller investig alleg trump russia collus appear obvious partisan depart justic high rank offici whose wife work group opposit research trump paid democrat nation committe sound like lot high rank peopl collud tri prevent donald trump presid paul told fox news bill hemmer hill thursday never fan shut govern intent fan defend bill right though pic twitter com qj sc ep senat rand paul randpaul decemb paul refer last week bombshel top doj offici bruce ohr met key player creation infam trump dossier wife nelli ohr work fusion gp opposit research firm commiss unproven document bprtime investig high rank obama govern offici might collud prevent elect realdonaldtrump could wors waterg time investig high rank obama govern offici might collud prevent elect realdonaldtrump could wors waterg senat rand paul randpaul decemb',
 'washington reuter u suprem court wednesday appear pois throw corrupt convict former virginia governor robert mcdonnel move feder prosecutor fear could undermin abil bring crook politician justic one hour argument sever eight justic signal mcdonnel accept luxuri gift sweetheart loan businessman seek promot dietari supplement constitut crimin act voic concern broad interpret u anti corrupt law use feder prosecutor could crimin numer commonplac action politician u justic depart lawyer michael dreeben told justic overturn mcdonnel convict give politician leeway accept gift return certain action would recip corrupt mcdonnel lawyer noel francisco argu former governor conduct differ politician across unit state daili basi respond request donor constitu mcdonnel former republican parti rise star serv governor consid possibl vice presidenti candid wife maureen convict separ trial prosecutor trial describ luxuri lifestyl mcdonnel live thank virginia businessman jonni william includ vacat design cloth shoe rolex watch daughter wed golf outing liber conserv justic alik rais concern justic depart interpret u briberi law stephen breyer describ danger enorm power elect offici feder prosecutor would hold court endors justic depart posit rule due end june decis mcdonnel favor could limit type case feder prosecutor could bring politician futur requir action taken return bribe must exampl simpli arrang meet benefactor govern offici impact decis would depend far justic will go narrow scope corrupt law justic potenti could overturn convict issu narrow rule focus specif mcdonnel case includ judg instruct juri weigh evid rather find corrupt law use case flaw even convict overturn mcdonnel could face retrial chief justic john robert appear favor broad rule say statut mcdonnel convict could unconstitut vagu cover mani differ activ robert cite exampl businessman seek state tax break return open new plant robert wonder would consid corrupt act state governor accept invit businessman go fish trip discuss propos breyer justic anthoni kennedi said politician need guidanc know conduct potenti could prosecut law interpret broadli polit figur know suppos suppos breyer said trial laid bare rift marriag mcdonnel convict corrupt count includ conspiraci briberi extort take gift loan exchang promot dietari supplement call anatabloc made william compani star scientif william want mcdonnel press research virginia state univers conduct studi could help win u regulatori approv anatabloc judg sentenc mcdonnel two year behind bar suprem court last year said would report prison appeal ongo mcdonnel wife found guilti nine crimin count receiv one year sentenc remain prison pursu separ appeal sonia sotomayor one justic indic support prosecut suggest reason infer mcdonnel intent help william accept money gift justic appear troubl signal rule favor would send ruth bader ginsburg appear alarm idea offici abl accept payment arrang meet without face potenti prosecut offici could simpli say pay thousand dollar said mcdonnel one high level politician appeal crimin convict heard suprem court sat wife courtroom last oral argument justic current term mcdonnel lawyer contend former governor conduct constitut offici action exchang thing valu requir convict feder briberi law',
 'think year compani would longer bulli advoc fewer right women contrari land end prove simpli case compani recent featur legendari women right advoc feminist gloria steinem catalog websit legend seri featur individu made differ respect industri world larg howev mani anti choic advoc amus land end promot someon push women control bodi quit liter bulli end relationship steinem one pro lifer comment land end facebook page us love famili love children complet puzzl would promot vocal pro abort celebr landsend anti child want kill possibl futur custom messag us give live feed love cloth children children also live special need clearli whoa deviou guilt trip upon threat boycott ship everyth land end back compani took chanc succumb harass gave bulli appar cathol school also threaten end relationship compani uniform supplier well land end offici statement understand custom offend inclus interview recent catalog gloria steinem quest women equal thought good idea heard custom differ reason sincer apolog goal featur individu differ interest background made differ new legend seri take polit religi stanc liter said thought good idea featur someon stood women equal apolog way stand women land end sure may lost religi zealot could gain hell lot back admir courag uphold woman right bodi equal amongst peer societi thing land end still go lose custom time peopl stand women right major america featur imag via flickr',
 'someon happi current possibl secretari state expand search appar two new candid politician former current militari everyday joe even wall street exec might well big oil execut big oil exec one rex tillerson current ceo exxonmobil lee raymond former ceo exxonmobil exxonmobil biggest oil giant bloodi fantast put big oil charg depart state arguabl import cabinet posit could number reason trump insist taken iraq oil one come mind like though exxonmobil partner rosneft russia state own oil compani ultim putin charg rosneft exxonmobil putin partner could trump tri tie us close russia seem far plausibl also entir possibl trump think might abl use depart state busi interest nomin ceo although ceo oil compani exactli think case mention put someon posit could potenti abus purpos further busi interest abroad tillerson support idea man made climat chang exxonmobil posit pari climat accord favor howev tillerson also made million last year anoth wealthi busi insid build leve trump swamp higher flood rather drain trump kick victori tour today say america first indiana speech perhap delud think expand search secretari state big oil execut exactli howev realli mesh well everyday american thought meant said america first smack seriou cronyism fill cabinet wealthi wall street financi ceo washington insid polar opposit campaign tell exxonmobil ceo would secretari state tell whether even abl job trump either continu serv end curri favor somewher realli complet clueless watch short report rachel maddow msnbc learn donald trump expand secretari state search exxon execut http co qsxl pg bq maddow blog maddowblog decemb featur imag via screen captur embed video',
 'first half debat donald trump seem bog distract sniffl peddl week lucr conspiraci hillari clinton sick command chief one must ask trump stop sniffl sick hold back tear pummel clinton howard dean former head dnc presidenti candid unconvent answer drug dean contributor msnbc tweet last night notic trump snif time coke user howard dean govhowarddean septemb trump support took twitter express outrag complet forget prefer candid spent week fuel sexist attack clinton stamina abil hey get offend dean point could obviou trump protect cocain traffick serv proper jail time pull string justic system consid releas medic record know advers effect drug done bodi mental state cours trump deni sniffl even though rancid sound heard million watcher across countri globe republican nomine deni sick beg question els could dean assert assert factual ground stand iron see trump support react conspiraci made candid perhap trump think long hard tri paint clinton anyth debat show one thing hillari came top trump happi littl fun petul behavior howard dean featur imag via joe readl getti imag',
 'reuter electr gener florida power light said thursday shut two nuclear power plant irma come ashor power hurrican fpl subsidiari nextera energi inc gener enough power million home turkey point st luci plant along florida atlant coast feet meter sea level safe shut nuclear plant well advanc hurrican forc wind final plan shutdown fpl spokesman rob gould told news confer compani adjust plan necessari depend upon path storm gould said would comment exactli plant would taken long could shut energi depart said late thursday nuclear regulatori commiss expect turkey point close friday even st luci shut hour later depend storm path irma categori hurrican top saffir simpson hurrican wind scale pack wind mile km per hour present forecast model show hit tip florida sunday morn rake whole state move north peninsula follow coupl day miami base nation hurrican center said fpl say invest billion protect electr grid sinc last major hurrican damag power facil florida grid hurrican proof irma stay path mani fpl custom lose power gould said compani serv million power custom across nearli half florida may physic rebuild part power system gould said could take week longer irma worst fear realiz said gould said fpl might turn substat ahead major flood techniqu could help compani restor power faster floodwat reced rather keep allow storm damag fpl nuclear plant protect thick concret reinforc steel like mani plant around world bolster fukushima nuclear disast japan gould said seri explos meltdown occur fukushima nuclear plant massiv earthquak unleash power tsunami shut facil cool system led meltdown',

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(corpus).toarray()

In [16]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
y = messages_sample['label'].values

In [18]:
y

array([0, 1, 1, ..., 0, 0, 1])

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42
)

In [20]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [21]:
y_pred = model.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.955

In [23]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       310
           1       0.96      0.95      0.95       290

    accuracy                           0.95       600
   macro avg       0.96      0.95      0.95       600
weighted avg       0.96      0.95      0.95       600

In [24]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[297  13]
 [ 14 276]]

In [25]:
from sklearn.metrics import roc_auc_score

y_prob = model.predict_proba(X_test)[:,1]

auc = roc_auc_score(y_test, y_prob)

print(auc)

0.9931701890989989

In [26]:
from sklearn.model_selection import GridSearchCV

params = {
    "C":[0.01,0.1,1,10],
    "solver":["liblinear","lbfgs"]
}

grid = GridSearchCV(
    LogisticRegression(),
    params,
    cv=5
)

grid.fit(X_train,y_train)

print(grid.best_params_)

{'C': 10, 'solver': 'liblinear'}

In [27]:
import pickle

pickle.dump(model,open("model.pkl","wb"))

pickle.dump(tfidf,open("vectorizer.pkl","wb"))